import { NextResponse } from 'next/server';
import { defaultClimateStats, defaultArticles } from '../../../lib/content';
import { fetchClimateNewsItems, formatClimateNewsForPrompt } from '../../../lib/news';
import { parseClimateArticleFeed, type ClimateArticleFeed } from '../../../lib/gemini-schema';

export const runtime = 'nodejs';

async function fetchGeminiArticles(context: string): Promise<ClimateArticleFeed | null> {
    const apiKey = process.env.GEMINI_API_KEY;
    const model = process.env.GEMINI_MODEL ?? 'gemini-1.5-pro';

    if (!apiKey) {
        return null;
    }

    const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
        {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                generationConfig: {
                    temperature: 0.7,
                    responseMimeType: 'application/json',
                },
                contents: [
                    {
                        parts: [
                            {
                                text: [
                                    'You are generating a climate news feed for a premium editorial portal.',
                                    'Use the RSS source context below to write structured JSON only.',
                                    'Return an object shaped exactly like this:',
                                    '{"articles":[{"title":"string","full_article_markdown":"string","meta_description":"string","suggested_image_query":"string"}]}',
                                    'Requirements:',
                                    '- Write 3 to 6 articles.',
                                    '- Each article must be grounded in the source context.',
                                    '- full_article_markdown must include sections titled Why, Impact, and Solutions.',
                                    '- meta_description should be 140 to 160 characters.',
                                    '- suggested_image_query should be a concise Unsplash search phrase.',
                                    '- Do not include markdown fences, commentary, or any meta-talk like "Here is your article", "Generated by AI", or "This article contains". Only pure journalistic content.',
                                    '- Focus on factual reporting grounded in the source context.',
                                    '',
                                    'RSS source context:',
                                    context,
                                ].join('\n'),
                            },
                        ],
                    },
                ],
            }),
        },
    );

    if (!response.ok) {
        return null;
    }

    const payload = (await response.json()) as {
        candidates?: Array<{
            content?: {
                parts?: Array<{
                    text?: string;
                }>;
            };
        }>;
    };

    const text = payload.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
        return null;
    }

    try {
        return parseClimateArticleFeed(text);
    } catch {
        return null;
    }
}

async function resolveUnsplashImage(query: string): Promise<string> {
    const accessKey = process.env.UNSPLASH_ACCESS_KEY;

    if (!accessKey) {
        return '';
    }

    const response = await fetch(
        `https://api.unsplash.com/photos/random?query=${encodeURIComponent(query)}&orientation=landscape`,
        {
            headers: {
                Authorization: `Client-ID ${accessKey}`,
            },
        },
    );

    if (!response.ok) {
        return '';
    }

    const payload = (await response.json()) as {
        urls?: {
            regular?: string;
        };
    };

    return payload.urls?.regular ?? '';
}

export async function GET() {
    const newsItems = await fetchClimateNewsItems();
    const newsContext = formatClimateNewsForPrompt(newsItems);
    const generated = newsContext ? await fetchGeminiArticles(newsContext) : null;

    const articles = await Promise.all(
        (generated?.articles ?? defaultArticles).map(async (article, index) => {
            const fallbackImage = defaultArticles[index % defaultArticles.length]?.image_url ?? '';
            const resolvedImage = await resolveUnsplashImage(article.suggested_image_query);

            return {
                ...article,
                image_url: resolvedImage || article.image_url || fallbackImage,
            };
        }),
    );

    return NextResponse.json({
        source: generated ? 'gemini' : 'fallback',
        articles,
        stats: defaultClimateStats,
        sources: newsItems,
        fetchedAt: new Date().toISOString(),
    });
}
